version: '3'

services:
  typer99:
    container_name: typer99
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SOCKET_URL=wss://typer99-api.mewo.gay
    ports:
      - "3003:3003"  # Frontend
      - "3004:3004"  # Backend socket server
    networks:
      - traefik
    labels:
      # Frontend routing
      - "traefik.enable=true"
      - "traefik.http.routers.typer99.rule=Host(`typer99.mewo.gay`)"
      - "traefik.http.routers.typer99.entrypoints=websecure"
      - "traefik.http.routers.typer99.tls=true"
      - "traefik.http.services.typer99.loadbalancer.server.port=3003"

      # Backend API routing
      - "traefik.http.routers.typer99-api.rule=Host(`typer99-api.mewo.gay`)"
      - "traefik.http.routers.typer99-api.entrypoints=websecure"
      - "traefik.http.routers.typer99-api.tls=true"
      - "traefik.http.services.typer99-api.loadbalancer.server.port=3004"

networks:
  traefik:
    name: traefik
    external: true